version: '3'

tasks:
  format:
    sources:
      - apps/yap/src/*.erl
    cmds:
      - rebar3 fmt "apps/yap/src/*.erl"
  type-check:
    sources:
      - apps/yap/src/*.erl
    cmds:
      - rebar3 gradualizer
  build:
    sources:
      - apps/yap/src/*.erl
    deps:
      [format, type-check]
    cmds:
      - rebar3 compile
  test:
    deps:
      [build]
    silent: true
    cmds:
      - for: ['lexer', 'parser']
        cmd: echo "Testing {{ .ITEM }} module..."; erl -pa _build/default/lib/yap/ebin/ -eval '{{ .ITEM }}:test(), halt().' -noshell 
  run-*:
    deps:
      [build]
    vars:
      TARGET: '{{index .MATCH 0}}'
    cmds:
      - escript _build/default/lib/yap/ebin/{{.TARGET}}.beam {{.CLI_ARGS}}
  repl:
    deps:
      [build]
    cmds:
      - erl  -pa _build/default/lib/yap/ebin/
